### ISSUE TITLE
Deallocation for responses is unclear.

### ISSUE THREAD

**Issue by brendandburns** [WebAssembly/wasi-http#18]
It's not entirely clear when in the process a response is actually sent. Is it when `finish-outgoing-stream` is called? Is it when `drop-response` is called (or `drop-outparam`)

We may want to add an explicit `send-response` method.

The reason for this need is because we need to explicitly send the response before we free the resources associated with the stream or the response objects.

cc @lukewagner

**Comment by lukewagner** [comment]
(sorry for slow reply; back now) Good question.  I was expecting that the response starts streaming back as soon as possible, which is when `set-response-outparam` is called.  But this should be explained in the comments, so filed #19.
