### ISSUE TITLE
Suggest to use git submodules for deps 

### ISSUE THREAD

**Issue by Mossaka** [WebAssembly/wasi-http#20]
For the time being, it will run out of sync for deps and their respective repos. I have observed that the `blocking-splice` function is missing from the wasi-io dep in this repo, probably due to the lack of sync. I'd suggest that until we have registry ready for wits, we can use git submodules to keep the deps as subdirectory of this repo.

**Comment by Mossaka** [comment]
I just realized that there isn't really a `wasi-io` repo that contains **only** the wit files, and thus the idea of using `git submodule` will inevitably clone non-wit files down...

**Comment by lukewagner** [comment]
I agree we need to improve our automation here around how we handle deps to get out of this manual-vendoring situation, but yeah, I guess `git submodule` isn't quite an easy fix here.  In the meantime I'll just update the deps manually now and feel free to file PRs that update them in the future (just by copying the files over).

**Comment by lukewagner** [comment]
[Updated](https://github.com/WebAssembly/wasi-http/commit/53e2d258ae3008d254bda79ec958355ded8751a9)

**Comment by Mossaka** [comment]
Per our dicussion from the last component model meeting, I'd like to put this option on the table. Could we tell wit-bindgen that the folders in `deps` are git repos that share the same structures. e.g. in root of each repo, there is a `wit` folder that contains the wit files. This will allow wit-bindgen to fetch the needed wit files and use git submodules to manage these repos. @lukewagner

**Comment by lukewagner** [comment]
That doesn't sound like a bad idea; but I guess this depends on the overall plan we make for the Wit tooling to support these sorts of modular interface development workflows in GitHub.

**Comment by Mossaka** [comment]
Checkout this repo: https://github.com/rvolosatovs/depit
