### ISSUE TITLE
Field values aren't guaranteed to be ASCII

### ISSUE THREAD

**Issue by lann** [WebAssembly/wasi-http#28]
The HTTP spec _recommends_ but does not _require_ that field values are ASCII:

https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#rfc.section.5.5.p.4

> Field values are usually constrained to the range of US-ASCII characters [USASCII]. Fields needing a greater range of characters can use an encoding, such as the one defined in [RFC8187]. Historically, HTTP allowed field content with text in the ISO-8859-1 charset [ISO-8859-1], supporting other charsets only through use of [RFC2047] encoding. Specifications for newly defined fields SHOULD limit their values to visible US-ASCII octets (VCHAR), SP, and HTAB. A recipient SHOULD treat other allowed octets in field content (i.e., obs-text) as opaque data.

Currently, field values are represented by `string`s, but this leaves some ambiguity in how to represent non-ASCII values (e.g. `"\xff"`). A couple of options:

- Change the field value type to `list<u8>`
- Document that field values are transcoded from latin1

**Comment by acfoltzer** [comment]
Yes, we definitely need to support the [`obs-text`](https://www.rfc-editor.org/rfc/rfc9110#section-5.5-2) grammar in field values. I support the `list<u8>` option, as an application that needs the actual bytes would end up with a very roundabout re-encoding step to recover the bytes from the utf8→latin1 transcoding.

**Comment by PiotrSikora** [comment]
+1 to `list<u8>`.

It actually _cannot_ be an UTF-8 string, since some valid HTTP field values are invalid UTF-8 characters.

**Comment by acfoltzer** [comment]
> It actually _cannot_ be an UTF-8 string, since some valid HTTP field values are invalid UTF-8 characters.

I think the suggestion was to first interpret the contents as latin1 and then transcode to UTF-8, which would be possible but also very awkward. `list<u8>` is the rightful winner 🙂
