### ISSUE TITLE
wasi-http-proxy

### ISSUE THREAD

**Issue by Mossaka** [WebAssembly/wasi-http#30]
What's the plan for [wasi-http-proxy](https://github.com/WebAssembly/wasi-http-proxy) repo? It looks like that repo hasn't been updated for years and still used the old WITX syntax. I believe the work here matches or even takes over that repo. FYI @lukewagner

**Comment by lukewagner** [comment]
Looks like it might've been created as a placeholder that never got filled in.  @sunfishcode maybe we can delete it?

**Comment by mikkelhegn** [comment]
Propse to close this issue as the wasi-http-proxy repo doesn't exist anymore. @Mossaka @lukewagner
