### ISSUE TITLE
Are headers semantically passed by value or by (mutable) reference?

### ISSUE THREAD

**Issue by dicej** [WebAssembly/wasi-http#38]
When I pass a `headers` parameter to `new-outgoing-response` and then edit those headers prior to passing the response to the host via `set-response-outparam`, should the edits be reflected in the response?  And what if I edit the headers _after_ calling `set-response-outparam`?  Analogous questions apply for outgoing requests.

**Comment by lann** [comment]
I think ideally `outgoing-response` would hold a shared reference to `headers`. Maybe the best approximation we could do would be calling the result of mutation in that scope "unspecified behavior"?

**Comment by lukewagner** [comment]
+1 to what @pchickey said.

That does mean that there is an unavoidable race if you hold onto a handle to `headers` after you pass an `outgoing-request` pointing to that same `headers` to `outgoing-handler.handle`.  I'll file a PR to document this case.

**Comment by dicej** [comment]
To be clear, I do understand about reference-counted resources, and that they imply mutable aliasing for a type like `fields`.  However, we have the option to say e.g. `new-outgoing-response` makes a private, immutable copy of `headers` if we _want_ to.  I.e. mutable aliasing is a choice rather than an inevitable consequence of the type of resource we're using.

Anyway, I'm fine with the consensus here and look forward to the documentation PR.  Thanks, all!

**Comment by lukewagner** [comment]
Yes, good point, that is a reasonable alternative to consider.  If we didn't have the future option of expressing exclusive ownership at the interface level, I'd want to more carefully dig into that option, b/c it does avoid some real composability footguns.

#43 is up, PTAL
