### ISSUE TITLE
new-outgoing-request should return a Result

### ISSUE THREAD

**Issue by brendandburns** [WebAssembly/wasi-http#44]
There are lots of reasons why a call to `new-outgoing-request` could fail, right now there's no way to tell the guest why something failed other than returning a NULL pointer.

**Comment by lukewagner** [comment]
Ah, good question.  I was assuming that the only failure case here was the memory allocation of the request header (where we generally just trap on small-allocation failures), with all the interesting stuff happening async and reflected in the results of subsequent method calls, but are there other failure modes you're seeing show up in your implementation?

**Comment by lukewagner** [comment]
Ah, right, thanks, I'll file a PR shortly.
