### ISSUE TITLE
Consider adding `get-incoming-request` and `set-outgoing-response` functions

### ISSUE THREAD

**Issue by dicej** [WebAssembly/wasi-http#77]
Recently I was working with @guybedford on adding support for `wasi:http/incoming-handler` to [wasi-virt](https://github.com/bytecodealliance/WASI-Virt).  After a bit of research and discussion with Guy and Alex, we came to the conclusion that, although such a feature is technically possible, it can't be expressed in WIT as currently defined and thus would require a challenging amount of low-level bytecode manipulation.  Further details can be found [here](https://bytecodealliance.zulipchat.com/#narrow/stream/219900-wasi/topic/.60wasi-http.60.20middleware.20is.20infeasible.3F/near/402557515).

Our plan for the time being is to wait until WASI Preview 2 ships, then update WIT and its tooling to support distinguishing between imported and exported versions of an interface, which will make the above feature much easier to implement.  However, that means we would ship WASI Preview 2 without a practical means to virtualize `wasi-http`, which would be a bit embarrassing given that virtualization is one of the big reasons we're moving to the component model.

It occurred to me over the weekend that an alternative approach would be easy to implement: add `get-incoming-request` and `set-outgoing-response` functions to `wasi-http`.  As an alternative to exporting a `incoming-handler#handle` function, a guest could export `wasi:cli/run#run` and import `get-incoming-request` and `set-outgoing-response`, similar to how it uses `wasi:cli/environment#get-arguments` to get CLI arguments.  The advantage to that mode of operation is that it is import-based and thus easy to virtualize the same way `wasi-virt` handles the rest of WASI -- there's no need to bypass WIT and construct multiple levels of indirection to deal with the component model's inability to refer to exported resource types in imported functions.  As a bonus, guest language implementations such as Go's WASI support, which do not yet have a general export capability, would be able to use `wasi-http` to handle incoming requests.

The signature for `get-incoming-request` could be either `func() -> option<incoming-request>` or `func() -> incoming-request` depending on how we wanted it to behave when the guest already has the `incoming-request` handle (i.e. should it trap, or should the host use reference counting, or should it return `none`?).  Likewise, `set-outgoing-response` could either trap if called redundantly or return a `bool` or `result`.  First, though, I'd like to get feedback on the overall idea.

To be clear: I don't think we should be `export`-phobic in WASI forever -- just that given the current state of WIT and ecosystem tooling, this might be the most practical option.

**Comment by dicej** [comment]
See also https://github.com/WebAssembly/component-model/issues/272, which is one of the reasons why virtualizing guest-exported functions is problematic.

**Comment by pchickey** [comment]
Understood that this is currently a blocker for wasi-virt and anything else using the present set of wit tools, but as far as I understand this isn't a fundamental problem with the component model's type system, just in the way its currently accessible through wit.

Right now we have tagged a release candidate in wasi-http and the rest of the Preview 2 launch proposals, and would like to keep them stable between now and the launch of Preview 2 if possible. Given that this seems to have some sort of path to resolution in by working on wit and other implementation details, and not on the specs themselves, I'd like to hold off on taking this sort of radical redesign approach to resolving this usability problem and focus on other paths to a solution unless all of those are exhausted.

**Comment by dicej** [comment]
@pchickey that's fine with me.  To be clear: I'm not proposing we get rid of `wasi:http/incoming-handler#handle`, so this would purely be an additive and thus backwards-compatible change.  But yeah, I don't want to distract from getting Preview 2 shipped.

**Comment by dicej** [comment]
Guy and I discussed this further, and it seems we can get the benefit of interface I proposed above without actually making it part of the standard.  We can make it an implementation detail of `wasi-virt` (e.g. `wasi-virt:http/incoming-handler`, used internally but not exposed to to users).
