### ISSUE TITLE
Does Wasmtime provide too many interfaces for the `proxy` world?

### ISSUE THREAD

**Issue by alexcrichton** [WebAssembly/wasi-http#79]
The [current definition of the `proxy` world](https://github.com/WebAssembly/wasi-http/blob/2befff608aa362aef20d79888b993787acd2f010/wit/proxy.wit#L18) has a TODO which indicates to me that it's known that there are more interfaces there than there should be. The Wasmtime implementation of providing imports for proxies however [delegates to the `command` module](https://github.com/bytecodealliance/wasmtime/blob/2e8e09a6dbc0bc1ab9eb3604bef0eee8f618c5fd/crates/wasi-http/src/proxy.rs#L28-L30) which provides [lots of interfaces](https://github.com/bytecodealliance/wasmtime/blob/2e8e09a6dbc0bc1ab9eb3604bef0eee8f618c5fd/crates/wasi/src/preview2/command.rs#L30-L54), some of which aren't listed in the `proxy` world such as:

* `wasi:filesystem/{types,preopens}`
* `wasi:cli/{exit,environment,terminal_*}`
* `wasi:sockets/*`

This is an issue which poses the question about what to fix here. Should Wasmtime's definition be trimmed down? Or should the `proxy` world grow more `import`s?

**Comment by lukewagner** [comment]
I think it's fine and even expected that each concrete host will provide a superset of the WASI-standard worlds that the host supports.  I could however imagine adding a runtime flag to Wasmtime that says "restrict yourself to world `X`" (where X could be `"wasi:http/proxy"` or `"wasi:cli/command"` or, in the future with registry integration, any published world) and this would be valuable for two reasons:
1. developers could test that the component they produced indeed only depends on the target world
2. wasmtime CLI users get a nice succinct way to control the capabilities provided to the component they want to run, analogous to the [permissions feature of deno](https://docs.deno.com/runtime/manual/basics/permissions)

If you had this feature, there is still a question of defaults and whether, by default, `wasmtime serve` enables everything or just some default world, but that's separable.

Thus, I'd propose that the answer to your question is that `wasi:http/proxy` stays as is (and in a P3 timeframe deletes those imports tagged with TODOs).

**Comment by lukewagner** [comment]
I could imagine defining a `wasmtime:serve/default` world that `include`s `wasi:http/proxy` and adds whatever else, and you could say "this is the world that is targeted by default".  I think this matches what most production embeddings of Wasmtime would do, s/`wasmtime`/`company-name`/, so we could think of wasmtime as just the generic/vanilla example of this.

**Comment by alexcrichton** [comment]
I've opened https://github.com/bytecodealliance/wasmtime/pull/7597 to address the Wasmtime side of this.

**Comment by alexcrichton** [comment]
I'll also close this since this is a Wasmtime issue, not a spec issue.
