### ISSUE TITLE
Should fields.get handle casing lookups?

### ISSUE THREAD

**Issue by guybedford** [WebAssembly/wasi-http#81]
It might make sense for `fields.get` to support arbitrary casing.

Here's how it might work:

* The fields internal table representation is always based on lowercased strings
* Each field entry then has an "exact case" property which was the casing used by its first setter
* For all gets and sets, we lookup the lowercasing.
* Deleting a field would delete the casing information, so the first setter would then win again

**Comment by lukewagner** [comment]
Yes, I think wasi-http should do a case-insensitive lookup, I think specified exactly the same way as WHATWG Fetch.  I've been planning to add a bunch more behavior spec text (not changing WIT, just documented behavior) to wasi-http and this is on that list, so happy to leave this issue open until this behavior is documented.

**Comment by guybedford** [comment]
Thanks for answering the question here - I've implemented this behaviour in the jco implementation.
