### ISSUE TITLE
Pass a headers pointer into incoming-response-headers

### ISSUE THREAD

**Issue by brendandburns** [WebAssembly/wasi-http#9]
For similar reasons to #8 it is challenging to implement returning headers for an incoming response because it returns a fields structure, while it is possible to implement this, I think it makes more sense to leave the memory allocation on the guest side and instead pass a pointer to a headers object into the incoming-response-headers function. (`get-headers(incoming-response, ptr, len)`)

**Comment by lukewagner** [comment]
In this case, the returned integer is an index to a `fields` resource, which avoids eagerly copying all the headers into linear memory at once.  I think this is an important ability to maintain, but it is a good question of whether we should perhaps add a new method for when you want to bulk-copy over all the contents of the headers into linear memory at once.

**Comment by brendandburns** [comment]
Yes, but both `fields-get` and `fields-entries` require returning `string` to the caller which means that the host needs to be able to allocate memory in the guest's memory space which isn't obvious how to implement (same as #8).

So bulk is part of it, but managing memory allocation in the guest from the host implementation is the bigger challenge.

**Comment by lukewagner** [comment]
(Sorry for the slow replies; at a conference this week.) Yes, that's not clear from the signatures (although perhaps the generated headers should include this information in comments).  Instead, the protocol for allocation/ownership is specified by the Canonical ABI which says, for every type, how to "lift" (read) and "lower" (write) the type out of and into linear memory.  In the case of lists, the main rule is [here](cargo install --git https://github.com/bytecodealliance/wit-bindgen wit-bindgen-cli).  To summarize, the memory is `realloc`ed in the guest, then the host writes the elements (which, for `list<string>` are themselves `i32` pairs pointing to `realloc`ed string conents), and finally returns ownership of the list to the import caller.

**Comment by brendandburns** [comment]
I discussed this somewhat more in-depth and it seems that the overall wit approach is going to be to enable someone to provide a buffer, but this mechanism is not currently available. I'm going to close this for now, but leave #8 open.
